### ISSUE TITLE
# when not a comment

### ISSUE THREAD

**Issue by werebear73** [miconda/vscode-kamailio-syntax#4]
This is another # symbol as part of a regular expression issue being interpreted as comment when it shouldn't be.

Example:
`$tU = $(tU{re.subst,/$avp(techprefix)[#*]//});`

Everything after the # symbol is interpreted as a comment.

Daniel, 

I will work to fix this soon.  Just wanted to put the issue in, in case, anyone else was having this issue and as a reminder that I need to come back and fix this like the other one.

Sam

**Comment by miconda** [comment]
The latest version (just published) should handle properly the presence of `#` in any transformations, no longer being needed  to handle it for re subst.

**Comment by werebear73** [comment]
Thanks, Daniel.
