### ISSUE TITLE
Please bring this extension for Visual Studio 2022

### ISSUE THREAD

**Issue by soroshsabz** [miconda/vscode-kamailio-syntax#7]
ITNOA

Visual Studio 2022 language services is near to vscode, so please add this extension for Visual Studio 2022

Please see https://docs.microsoft.com/en-us/visualstudio/extensibility/adding-an-lsp-extension?view=vs-2022

thanks

**Comment by miconda** [comment]
I don't have Visual Studio 2022, so I can't help. Iirc, the syntax for VSCode was more or less regexp based, not LSP.

If anyone wants to make a pull request, it's more than welcome.

**Comment by soroshsabz** [comment]
@miconda I added visual studio extension https://github.com/soroshsabz/visualstudio-kamailio based on your syntax, and link to your repo

thanks a lot ;)
